server:
  port: 8085

spring:
  application:
    name: configuration-dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RahulJadhav926/micro-configuration-server
          clone-on-start: true
